# Generated by Django 4.1.2 on 2022-10-26 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('trends', models.IntegerField()),
                ('is_partial', models.BooleanField()),
                ('search_keyword', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='RegionInterests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
