# Generated by Django 4.1.2 on 2022-10-29 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_trends', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='regioninterests',
            name='keyword1',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='regioninterests',
            name='keyword2',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='regioninterests',
            name='region',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='regioninterests',
            name='trends',
            field=models.IntegerField(null=True),
        ),
    ]
