# Generated by Django 4.1.2 on 2022-10-26 22:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('google_trends', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalInterestKeyWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_keyword', models.CharField(max_length=250)),
            ],
        ),
        migrations.RemoveField(
            model_name='historicalinterest',
            name='search_keyword',
        ),
        migrations.AddField(
            model_name='historicalinterest',
            name='search_key',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, related_name='search_key', to='google_trends.historicalinterestkeyword'),
            preserve_default=False,
        ),
    ]
